repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.5
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -q
        language: system
        pass_filenames: false
