version: "3.8"
services:
  inference_server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/textgen
    depends_on:
      - db
    volumes:
      - type: volume
        source: models
        target: /models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: textgen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  models:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /dev/nvme0n1p2
  postgres_data:
