"""Add foreign key constraints and complete schema

Revision ID: b6440a1a2294
Revises: 001
Create Date: 2025-07-09 18:22:27.676441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6440a1a2294'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_characters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('ai_characters_url_name_key', 'ai_characters', type_='unique')
    op.drop_index('ix_ai_num_interactions', table_name='ai_characters')
    op.drop_index('ix_ai_updated', table_name='ai_characters')
    op.drop_index('ix_ai_user_id', table_name='ai_characters')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'voices', 'users', ['user__id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voices', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_index('ix_ai_user_id', 'ai_characters', ['user__id'], unique=False)
    op.create_index('ix_ai_updated', 'ai_characters', ['updated'], unique=False)
    op.create_index('ix_ai_num_interactions', 'ai_characters', ['num_interactions'], unique=False)
    op.create_unique_constraint('ai_characters_url_name_key', 'ai_characters', ['url_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('ai_characters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
